# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: UserBundle:User
                property: username

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                # field names for the username and password fields:
                username_parameter: _username
                password_parameter: _password
                # default_target_path: default_security_target
                # always_use_default_target_path: true
            logout:
                path:   /logout
                target: /login
                
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
            
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/user/index, roles: ROLE_ADMIN }
        - { path: ^/user/add, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/edit, roles: ROLE_ADMIN }
        - { path: ^/user/view, roles: [ROLE_ADMIN] }
        - { path: ^/user/delete, roles: ROLE_ADMIN }
        - { path: ^/image/index, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/image/add, roles:  ROLE_USER }
        - { path: ^/image/edit, roles: ROLE_USER }
        - { path: ^/image/delete, roles: ROLE_USER }  
        
       