image_index:
    path:     /index
    defaults: { _controller: UserBundle:Image:index }

image_add:
    path:     /add
    defaults: { _controller: UserBundle:Image:add }

image_create:
    path:     /create
    defaults: { _controller: UserBundle:Image:create }
    methods:  POST

image_edit:
    path:     /edit/{id}
    defaults: { _controller: UserBundle:Image:edit }

image_update:
    path:     /update/{id}
    defaults: { _controller: UserBundle:Image:update }
    methods:  [POST, PUT]

image_view:
    path:     /view/{id}
    defaults: { _controller: UserBundle:Image:view }

image_delete:
    path:     /delete/{id}
    defaults: { _controller: UserBundle:Image:delete }

image_ok:
    path:     /ok/{id}
    defaults: { _controller: UserBundle:Image:aprove }

image_redirect_add:
    path: /create
    defaults:
        _controller: UserBundle:Image:add
        path: /add
        permanent: true

image_custom:
    path:     /custom
    defaults: { _controller: UserBundle:Image:custom }
    
image_process:
    path:     /process/{id}
    defaults: { _controller: UserBundle:Image:process }
    methods:  [POST, PUT]    

image_redirect_edit:
    path: /update/{id}
    defaults:
        _controller: UserBundle:Image:edit
        path: /edit/{id}
        permanent: true